# -*- coding: utf-8 -*-
from . import (
    demand_order_type,
    mrp_bom,
    mrp_demand_line,
    mrp_demand_order,
    mrp_demand_raw_material,
    mrp_demand_working_time,
    mrp_production,
    mrp_workcenter,
    mrp_workcenter_productivity,
    mrp_workingtime_workcenter,
    mrp_workorder,
    plan_order,
    plan_order_line,
    procurement_group,
    product_attribute_custom_value,
    queue_job,
    res_company,
    res_config_settings,
    stock_move,
    stock_picking,
    stock_rule,
)
